In [41]:
import pickle
import scanpy as sc
import anndata as ad
import numpy as np
import pandas as pd
import scipy.sparse as sp
import h5py
plate='plate2'
raw_h5ad_path = f"/mnt/shared-storage-gpfs2/beam-gpfs02/yulang/datasets/by_plate/hvg/{plate}_hvg.h5ad"
adata = sc.read_h5ad(raw_h5ad_path) 

# raw_h5_path = f"/mnt/shared-storage-gpfs2/beam-gpfs02/yulang/datasets/tahoe_holdout/holdout_{plate}.h5"
# adata = h5py.File(raw_h5_path, 'r')

In [42]:
uniq_df = adata.obs[['cell_line', 'cell_name']].drop_duplicates()
uniq_df

                     cell_line   cell_name
BARCODE_SUB_LIB_ID
01_001_053-lib_1000  CVCL_1119     CFPAC-1
01_001_082-lib_1000  CVCL_0292       HCT15
01_001_145-lib_1000  CVCL_1098   HepG2/C3A
01_001_175-lib_1000  CVCL_0131       A-172
01_001_181-lib_1000  CVCL_0399        LoVo
01_002_009-lib_1000  CVCL_1478   NCI-H1573
01_002_014-lib_1000  CVCL_1547     NCI-H23
01_002_041-lib_1000  CVCL_C466  hTERT-HPNE
01_002_128-lib_1000  CVCL_0023        A549
01_003_028-lib_1000  CVCL_0152      AsPC-1
01_003_050-lib_1000  CVCL_1731      SW 900
01_003_123-lib_1000  CVCL_0546       SW480
01_003_167-lib_1000  CVCL_0459    NCI-H460
01_004_142-lib_1000  CVCL_0028      AN3 CA
01_004_190-lib_1000  CVCL_1056        A498
01_005_150-lib_1000  CVCL_0179      BT-474
01_005_184-lib_1000  CVCL_0480      PANC-1
01_006_050-lib_1000  CVCL_0428  MIA PaCa-2
01_006_164-lib_1000  CVCL_0293     HEC-1-A
01_006_175-lib_1000  CVCL_1495   NCI-H1792
01_007_042-lib_1000  CVCL_1666   RPMI-7951
01_007_079-lib_1000  CVCL_1635  Panc 03.27
01_007_089-lib_1000  CVCL_0332     HS-578T
01_008_056-lib_1000  CVCL_0069    SK-MEL-2
01_009_131-lib_1000  CVCL_1097         C32
01_010_048-lib_1000  CVCL_1239          H4
01_011_141-lib_1000  CVCL_1724        SW48
01_012_020-lib_1000  CVCL_1550   NCI-H2347
01_012_057-lib_1000  CVCL_1381    LOX-IMVI
01_013_075-lib_1000  CVCL_1285       HOP62
01_013_118-lib_1000  CVCL_1517   NCI-H2030
01_013_130-lib_1000  CVCL_0099       SNU-1
01_013_138-lib_1000  CVCL_1717      SW1417
01_015_157-lib_1000  CVCL_0371    KATO III
01_020_119-lib_1000  CVCL_0366     SNU-423
01_021_054-lib_1000  CVCL_0359         J82
01_021_084-lib_1000  CVCL_1094      C-33 A
01_022_049-lib_1000  CVCL_0504         RKO
01_025_004-lib_1000  CVCL_1715     SW 1088
01_027_016-lib_1000  CVCL_0397      LS 180
01_027_135-lib_1000  CVCL_1693      SHP-77
01_028_149-lib_1000  CVCL_0334     Hs 766T
01_029_011-lib_1000  CVCL_0320       HT-29
01_044_054-lib_1000  CVCL_0218    COLO 205
01_068_006-lib_1000  CVCL_1125     CHP-212
01_071_064-lib_1000  CVCL_1055       A-427
01_179_118-lib_1000  CVCL_1716     SW 1271
03_019_074-lib_1000  CVCL_1577    NCI-H661
03_107_102-lib_1000  CVCL_1531   NCI-H2122
05_183_153-lib_1000  CVCL_1571    NCI-H596

In [10]:
adata.obs.head()

,sample,gene_count,tscp_count,mread_count,drugname_drugconc,drug,cell_line,sublibrary,BARCODE,pcnt_mito,S_score,G2M_score,phase,pass_filter,cell_name,plate
BARCODE_SUB_LIB_ID,,,,,,,,,,,,,,,,
01_001_053-lib_1000,smp_1591,2671,5629,6830,"[('Infigratinib', 0.5, 'uM')]",Infigratinib,CVCL_1119,lib_1000,01_001_053,0.016522,-0.265873,-0.313553,G1,full,CFPAC-1,plate2
01_001_082-lib_1000,smp_1591,2148,3173,3826,"[('Infigratinib', 0.5, 'uM')]",Infigratinib,CVCL_0292,lib_1000,01_001_082,0.025843,0.400794,0.520879,G2M,full,HCT15,plate2
01_001_145-lib_1000,smp_1591,683,886,1073,"[('Infigratinib', 0.5, 'uM')]",Infigratinib,CVCL_1098,lib_1000,01_001_145,0.029345,-0.019841,-0.032967,G1,full,HepG2/C3A,plate2
01_001_175-lib_1000,smp_1591,1845,2786,3368,"[('Infigratinib', 0.5, 'uM')]",Infigratinib,CVCL_0131,lib_1000,01_001_175,0.031587,-0.123016,-0.118498,G1,full,A-172,plate2
01_001_181-lib_1000,smp_1591,1228,1849,2226,"[('Infigratinib', 0.5, 'uM')]",Infigratinib,CVCL_0399,lib_1000,01_001_181,0.015143,0.023810,-0.008791,S,full,LoVo,plate2

In [8]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 670544149 stored elements and shape (5481420, 2000)>

In [7]:
adata.obsm["X_hvg"].min()

0.0